[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm ci --workspace=client']

[phases.build]
cmds = ['npm run build --workspace=client']

[start]
cmd = 'npm start --workspace=client'
